version: "3"
services:

    ga:
        image: ga:v1
        volumes:
            - "../../config/authn/keys:/etc/token/keys"
            - "../../config/ga/config.toml:/etc/ga/config.toml"
        environment:
            GA_DEBUG: "true"
            GA_SERVICE: authz
        depends_on:
            - api
        networks:
            - default
            - traefik
        labels:
            traefik.backend: authz
            traefik.frontend.rule: PathPrefixStrip:/authz
            traefik.docker.network: ga-deploy-traefik

    api:
        image: ooclab/authz:v0.9.1
        environment:
            DB_URI: "postgresql+pg8000://root:password@postgres:5432/authz"
        depends_on:
            - postgres
        labels:
            - "traefik.enable=false"

    postgres:
        image: postgres:10.5
        environment:
            POSTGRES_DB: authz
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        labels:
            - "traefik.enable=false"

networks:
    traefik:
        external:
          name: ga-deploy-traefik
