version: "3"
services:

    ga:
        image: ga:v1
        volumes:
            - "./config.toml:/etc/ga/config.toml"
        environment:
            GA_DEBUG: "true"
            GA_SERVICE: service
        depends_on:
            - api
        networks:
            - default
            - traefik
        labels:
            traefik.backend: service
            traefik.frontend.rule: PathPrefixStrip:/service
            traefik.docker.network: ga-deploy-traefik

    api:
        image: ooclab/service:v0.9
        environment:
            DB_URI: "postgresql+pg8000://root:password@postgres:5432/service"
            ETCD_ENDPOINTS: "etcd:2379"
            INTERNAL_APIGATEWAY: "http://ga:2998"
        depends_on:
            - postgres
        # service need access etcd
        # TODO: ga forward tcp to etcd ?
        networks:
            - default
            - traefik
        labels:
            - "traefik.enable=false"

    postgres:
        image: postgres:10.5
        environment:
            POSTGRES_DB: service
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        labels:
            - "traefik.enable=false"

networks:
    traefik:
        external:
          name: ga-deploy-traefik
