version: '3'
services:

    traefik:
        image: traefik:v1.7.2
        command: --api --docker
        ports:
            - "10080:80"     # The HTTP port
            - "18080:8080"   # The Web UI (enabled by --api)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - default
            - traefik
        labels:
            - "traefik.enable=false"

    etcd:
        image: quay.io/coreos/etcd:v3.3
        volumes:
            - ./etcd-data:/etcd-data
        ports:
            - 127.0.0.1:2379:2379
            - 127.0.0.1:2380:2380
        entrypoint: |
            /usr/local/bin/etcd
            --data-dir /etcd-data
            --name node1
            --initial-advertise-peer-urls http://127.0.0.1:2380
            --listen-peer-urls http://0.0.0.0:2380
            --advertise-client-urls http://0.0.0.0:2379
            --listen-client-urls http://0.0.0.0:2379
            --initial-cluster node1=http://127.0.0.1:2380
            --debug
        networks:
            - default
            - traefik
        labels:
            - "traefik.enable=false"

networks:
    traefik:
        external:
          name: ga-deploy-traefik
