version: "3"
services:

    ga:
        image: ga:v1
        volumes:
            - "./config.yml:/etc/ga/config.yml"
        environment:
            GA_DEBUG: "true"
        depends_on:
            - api
        networks:
            - default
            - traefik
        labels:
            traefik.backend: authn
            traefik.frontend.rule: PathPrefixStrip:/authn
            traefik.docker.network: ga-deploy-traefik

    api:
        image: ooclab/authn:v0.9
        environment:
            TOKEN_KEY_PATH: /etc/authn/keys
            DB_URI: "postgresql+pg8000://root:password@postgres:5432/authn"
        volumes:
            - "../../config/authn/keys:/etc/authn/keys"
        depends_on:
            - postgres
        labels:
            - "traefik.enable=false"

    postgres:
        image: postgres:10.5
        environment:
            POSTGRES_DB: authn
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        volumes:
            - "./pg-data:/var/lib/postgresql"
        labels:
            - "traefik.enable=false"

networks:
    traefik:
        external:
          name: ga-deploy-traefik
